### ISSUE TITLE
GoogleCloudStorage is not defined

### ISSUE THREAD

**Issue by donalbertico** [JSSolutions/meteor-google-cloud-storage#1]
when using your package, this var is not available trough the app

**Comment by vadym-vorobel** [comment]
@donalbertico did you import it like this:

`import { GoogleCloudStorage } from 'meteor/jss:google-cloud-storage'`

**Comment by donalbertico** [comment]
I didn't... Im not sure why you don't have to do this with other packages, and them vars are just available.
It works now thanks! @alonoslav 

very useful package if you prefer google storage instead of amazon s3

**Comment by vadym-vorobel** [comment]
@donalbertico you're welcome)

**Comment by hamedhemmati** [comment]
I get GoogleCloudStorage is not a constructor even when I do the import. If I don't do the import then it says it's not defined.

**Comment by trsdln** [comment]
@hamedhemmati Can't say what is wrong. Please, provide line with import and line with constructor call.
